#!/usr/bin/env python

import argparse
from clint.textui import colored, indent, puts




if __name__ == '__main__':


	parser = argparse.ArgumentParser( description='SPINE: A Cross-Platform Framework for Mobile Health Application Development.' )
	subparsers = parser.add_subparsers(help='general spine usage')

	# create the parser for the "generate" command
	parser_gen = subparsers.add_parser('generate', help='scaffold an application using the given generator')
	parser_gen.add_argument('name', type=str, action='store', default='newSpineApp', help='the name of the new application')
	parser_gen.add_argument('generator', type=str, action='store', default='spine', help='the spine generator')

	# create the parser for the "build" command
	parser_build = subparsers.add_parser('build', help='build the given spine application for the specified environment(s)')
	parser_build.add_argument('ios', action='store_true', default=False, help='compile for ios')
	parser_build.add_argument('android', action='store_true', default=False, help='compile for android')

	args = parser.parse_args()
	print args.accumulate(args.integers)

	# with indent(3, quote=colored.red(' >')):
	#     puts ('some random text')
	#     puts ('another text')
	#     with indent(3, quote=colored.green(' |')):
	#         puts('some more nested identation')
	#         puts('cool isn\'t?')
